core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('epigraphy.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

epigraphy/urls.py
from django.urls import path
from .import views
from .views import *
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path

urlpatterns = [

    path('', views.homepage, name="homepage"),
    path('place/<int:monument_id>/', views.monument_detail, name='monument_detail'),
    path('places/', views.monument_list, name='monument_list'),
    path('place/epigraphy/<int:epigraphy_id>/', views.epigraphy_detail, name='epigraphy_detail'),
    path('base/', views.base, name='base'),
    path('about/', about_view, name='about'),
    path('team/', team_view, name='team'),
    path('platform/', platform_view, name='platform'),

  

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

epigraphy/models.py
from django.db import models 
from storages.backends.s3boto3 import S3Boto3Storage  # Import the S3Boto3Storage

from ckeditor.fields import RichTextField
from .constants import *
from django.contrib import admin
from django.utils.html import format_html
    
def photos(instance, filename):
    title = instance.title
    return f'{title}/photos/{filename}'
def files(instance, filename):
    title = instance.title
    return f'{title}/files/{filename}'



class Epigraphy(models.Model):
    
    place = models.ForeignKey('Monument', on_delete=models.SET_NULL, null=True, help_text="Corresponding to Site")
    title = models.CharField(max_length=100, help_text="Enter the ID")
    short_name = models.CharField(max_length=100,)

    
    image_1 = models.ImageField(null=True,blank=True,upload_to=photos,storage=S3Boto3Storage(),)  
    image_2 = models.ImageField(null=True,blank=True,upload_to=photos,storage=S3Boto3Storage(),)
    image_3 = models.ImageField(null=True,blank=True,upload_to=photos,storage=S3Boto3Storage(),)
    image_4 = models.ImageField(null=True,blank=True,upload_to=photos,storage=S3Boto3Storage(),)  
    image_5 = models.ImageField(null=True,blank=True,upload_to=photos,storage=S3Boto3Storage(),)
    image_6 = models.ImageField(null=True,blank=True,upload_to=photos,storage=S3Boto3Storage(),)
    image_7 = models.ImageField(null=True,blank=True,upload_to=photos,storage=S3Boto3Storage(),)
    image_8 = models.ImageField(null=True,blank=True,upload_to=photos,storage=S3Boto3Storage(),)
    image_9 = models.ImageField(null=True,blank=True,upload_to=photos,storage=S3Boto3Storage(),)
    image_10 = models.ImageField(null=True,blank=True,upload_to=photos,storage=S3Boto3Storage(),)
                                  
                                  
                                  
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)

    past_location =  models.CharField(null=True, blank=True,max_length=1000)
    current_location =  models.CharField(null=True, blank=True,max_length=1000)

   
    
    object_type =  models.CharField(null=True, blank=True,max_length=600, choices=OBJECTTYPE)
    
    state_of_preservation =  models.CharField(null=True, blank=True,max_length=100, choices= STATEOFPRESERVATION)
    type_of_writing =  models.CharField(null=True, blank=True,max_length=200, choices=TYPEOFWRITING)
    language =  models.CharField(null=True, blank=True,max_length=50, choices=LANGUAGE)
    type_of_inscription =  models.CharField(null=True, blank=True,max_length=100, choices=TYPEOFINSCRIPTION)
    
    promoter =  models.CharField(null=True, blank=True,max_length=50, choices=PROMOTER)
    material =  models.CharField(null=True, blank=True,max_length=500, choices=MATERIAL)
    specific_material =  models.CharField(null=True, blank=True,max_length=100)
    administrative_district =  models.CharField(null=True, blank=True,max_length=100, choices=ADMINISTRATIVEDISTRICT)
    
    height =  models.CharField(null=True, blank=True,max_length=100)
    width =  models.CharField(null=True, blank=True,max_length=100)
    depth_diameter =  models.CharField(null=True, blank=True,max_length=100)
    letter_heights =  models.CharField(null=True, blank=True,max_length=100)

    
   
    #state_of_preservation =  models.CharField(null=True, blank=True,max_length=200)
    
    motivation =  models.CharField(null=True, blank=True,max_length=1000)

    day =  models.CharField(null=True, blank=True,max_length=100)
    month =  models.CharField(null=True, blank=True,max_length=100)

    year_from =  models.CharField(null=True, blank=True,max_length=100)
    year_to =  models.CharField(null=True, blank=True,max_length=100)
    
    
    description =  RichTextField(null=True, blank=True,default=None)
    bibliography =  RichTextField(null=True, blank=True,default=None)
    transcription_interpreted =  RichTextField(null=True, blank=True,default=None)
    transcription_diplomatic =  RichTextField(null=True, blank=True,default=None)
    translation =  RichTextField(null=True, blank=True,default=None)
    apparatus =  RichTextField(null=True, blank=True,default=None)
 
     
    full_epidoc_xml = models.FileField(null=True,blank=True,upload_to=files,storage=S3Boto3Storage(),)

    RTI_URL = models.URLField(null=True, blank=True,max_length = 100)
    
    three_dimensional_URL = models.URLField(null=True, blank=True,max_length = 100)

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    iconographic_elements = models.ManyToManyField("IconographicElement",  blank=True,)
  

    # Prepopulate from the title field the image_one
    def save(self, *args, **kwargs):
        if not self.image_1:
            self.image_1 = self.title
        super().save(*args, **kwargs)

        
    
    def __str__(self):
        return self.title
    
    
    
    

    class Meta:
        verbose_name = "Inscription"
        verbose_name_plural = "Inscriptions"



class Monument(models.Model):
    
    TYPE = (
        ('Castle', 'Castle'),
        ('Lintel', 'Lintel'),
    )
    
    title = models.CharField(max_length=100, help_text=" Site")
    type =  models.CharField(null=True, blank=True,max_length=20, choices=TYPE)
    
    site_image = models.ImageField(null=True,blank=True,upload_to=photos,storage=S3Boto3Storage(),)  
    
    three_dimensional_URL = models.URLField(null=True, blank=True,max_length = 100)
    three_360_URL = models.URLField(null=True, blank=True,max_length = 100)
    lat = models.FloatField(null=True, blank=True)
    long = models.FloatField(null=True, blank=True)
    location = models.CharField(max_length=100)
    date = models.CharField(max_length=100)
    description = RichTextField(null=True, blank=True,default=None)
    bibliography = RichTextField(null=True, blank=True,default=None)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
    class Meta:
        verbose_name = "Site"
        verbose_name_plural = "Sites"



class IconographicElement(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    url = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.name
   
     

epigraphy/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from .models import *



def base(request):
    return render(request, 'core/base.html',)

# HomePage
def homepage(request):
    monuments = Monument.objects.all()
    context = {
        'monuments': monuments
    }
    return render(request, 'core/index.html', context)

# Monument detail single monument with all epigraphy
def monument_detail(request, monument_id):
    monument = get_object_or_404(Monument, id=monument_id)
    iconographic_elements = IconographicElement.objects.all()
    epigraphy = monument.epigraphy_set.all()
    epigraphy_count = monument.epigraphy_set.count()
  

    context = {
        'monument': monument,
        'epigraphy': epigraphy,
        'iconographic_elements':iconographic_elements,
        'epigraphy_count':epigraphy_count,
        
    }
  
    return render(request, 'monument/monument_detail.html', context)

# List of all monuments 
def monument_list(request):
    monuments = Monument.objects.all()
    context = {
        'monuments': monuments
    }
    return render(request, 'monument/monument_list.html', context)


# epigraphy_detail

def epigraphy_detail(request, epigraphy_id):
    epigraphy = get_object_or_404(Epigraphy, pk=epigraphy_id)
    return render(request, 'epigraphy/epigraphy_detail.html', {'epigraphy': epigraphy})

# about page

def about_view(request):
    return render(request, 'about.html')
    
    
# Team page

def team_view(request):
    return render(request, 'team.html')
    
# Platform page

def platform_view(request):
    return render(request, 'platform.html')

templates/epigraphy/epigraphy_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block header %}
 {{ epigraphy.place}} / {{ epigraphy.title }} 

 
{% endblock %}
{% block content %}
 
{% if epigraphy.image_1 and epigraphy.image_1.url %}
  <a data-fancybox="image-gallery" href="{{ epigraphy.image_1.url }}">
    <img src="{{ epigraphy.image_1.url }}" style="max-width: 50%; height: auto;" alt="Image 1" title="Object One">
  </a>
{% endif %}
<br>
<br>
<br>
<div class="thumbnail-container">
  {% if epigraphy.image_2 and epigraphy.image_2.url %}
    <a data-fancybox="image-gallery" href="{{ epigraphy.image_2.url }}">
      <img src="{{ epigraphy.image_2.url }}" style="width: 100px;" alt="Image 2" title="Object One">
    </a>
  {% endif %}
  
  {% if epigraphy.image_3 and epigraphy.image_3.url %}
    <a data-fancybox="image-gallery" href="{{ epigraphy.image_3.url }}">
      <img src="{{ epigraphy.image_3.url }}" style="width: 100px;" alt="Image 3" title="Object One">
    </a>
  {% endif %}
  
  {% if epigraphy.image_4 and epigraphy.image_4.url %}
    <a data-fancybox="image-gallery" href="{{ epigraphy.image_4.url }}">
        <img src="{{ epigraphy.image_4.url }}" style="width: 100px;" alt="Image 4" title="Object One">
    </a>
  {% endif %}
  
  {% if epigraphy.image_5 and epigraphy.image_5.url %}
    <a data-fancybox="image-gallery" href="{{ epigraphy.image_5.url }}">
       <img src="{{ epigraphy.image_5.url }}" style="width: 100px;" alt="Image 5" title="Object One">
    </a>
  {% endif %}
  
  {% if epigraphy.image_6 and epigraphy.image_6.url %}
    <a data-fancybox="image-gallery" href="{{ epigraphy.image_6.url }}">
        <img src="{{ epigraphy.image_6.url }}" style="width: 100px;" alt="Image 6" title="Object One">
    </a>
  {% endif %}
   
  {% if epigraphy.image_7 and epigraphy.image_7.url %}
    <a data-fancybox="image-gallery" href="{{ epigraphy.image_7.url }}">
        <img src="{{ epigraphy.image_7.url }}" style="width: 100px;" alt="Image 7" title="Object One">
    </a>
  {% endif %}
  
  {% if epigraphy.image_8 and epigraphy.image_8.url %}
    <a data-fancybox="image-gallery" href="{{ epigraphy.image_8.url }}">
        <img src="{{ epigraphy.image_8.url }}" style="width: 100px;" alt="Image 8" title="Object One">
    </a>
  {% endif %}
  
  {% if epigraphy.image_9 and epigraphy.image_9.url %}
    <a data-fancybox="image-gallery" href="{{ epigraphy.image_9.url }}">
        <img src="{{ epigraphy.image_9.url }}" style="width: 100px;" alt="Image 9" title="Object One">
    </a>
  {% endif %}
  
  {% if epigraphy.image_10 and epigraphy.image_10.url %}
    <a data-fancybox="image-gallery" href="{{ epigraphy.image_10.url }}">
        <img src="{{ epigraphy.image_10.url }}" style="width: 100px;" alt="Image 10" title="Object One">
    </a>
  {% endif %}
</div>


  


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>
<script>
  $(document).ready(function() {
    $('[data-fancybox="graffito-gallery"]').fancybox({
      thumbs: {
        autoStart: true,
        axis: 'x',
      }
    });
  });
</script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>
<br>
<br>

   
 {% if epigraphy.title %}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{ epigraphy.title }} Information</h5>
    <table class="table table-striped">
      <tbody>
      {% endif %}
       {% if epigraphy.object_type %}
        <tr>
          <td><strong>Object type:</strong></td>
          <td>{{ epigraphy.get_object_type_display }}</td>
        </tr>
        {% endif %}
        
        {% if epigraphy.short_name %}
        <tr>
          <td><strong>Short Name:</strong></td>
          <td>{{ epigraphy.short_name }}</td>
        </tr>
        {% endif %}
        
        
        {% if epigraphy.type_of_writing %}
        <tr>
          <td><strong>Type of writing:</strong></td>
          <td>{{ epigraphy.get_type_of_writing_display }}</td>
        </tr>
        {% endif %}
        
        
        
        
        
         {% if epigraphy.year_from %}
        <tr>
          <td><strong>Year From:</strong></td>
          <td>{{ epigraphy.year_from }}</td>
        </tr>
        {% endif %}
        
        {% if epigraphy.year_to %}
        <tr>
          <td><strong>Year To:</strong></td>
          <td>{{ epigraphy.year_to }}</td>
        </tr>
        {% endif %}
        
         {% if epigraphy.day and epigraphy.month and epigraphy.year_from and epigraphy.year_to %}
        <tr>
          <td><strong>Date:</strong></td>
          <td>{{ epigraphy.day }} {{ epigraphy.month }} {{ epigraphy.year_from }}-{{ epigraphy.year_to }}</td>
        </tr>
        {% endif %}
        
        
    
     {% if epigraphy.height %}
        <tr>
          <td><strong>Height:</strong></td>
          <td>{{ epigraphy.height }}</td>
        </tr>
        {% endif %}
    
    
      {% if epigraphy.width %}
        <tr>
          <td><strong>Width:</strong></td>
          <td>{{ epigraphy.width }}</td>
        </tr>
        {% endif %}
        
     {% if epigraphy.depth_diameter %}
        <tr>
          <td><strong>Depth/Diameter:</strong></td>
          <td>{{ epigraphy.depth_diameter }}</td>
        </tr>
        {% endif %}
        

        {% if epigraphy.letter_heights %}
        <tr>
          <td><strong>Letter Heights:</strong></td>
          <td>{{ epigraphy.letter_heights }}</td>
        </tr>
        {% endif %}
        
         {% if epigraphy.promoter %}
        <tr>
          <td><strong>Promoter:</strong></td>
          <td>{{ epigraphy.get_promoter_display }}</td>
        </tr>
        {% endif %}
        
        {% if epigraphy.language %}
        <tr>
          <td><strong>Language:</strong></td>
          <td>{{ epigraphy.get_language_display }}</td>
        </tr>
        {% endif %}
        
        {% if epigraphy.type_of_inscription %}
        <tr>
          <td><strong>Type of inscription:</strong></td>
          <td>{{ epigraphy.get_type_of_inscription_display }}</td>
        </tr>
        {% endif %}
        
        {% if epigraphy.social_category %}
        <tr>
          <td><strong>Social category:</strong></td>
          <td>{{ epigraphy.social_category }}</td>
        </tr>
        {% endif %}
        
        {% if epigraphy.material %}
        <tr>
          <td><strong>Material:</strong></td>
          <td>{{ epigraphy.get_material_display }} {% if epigraphy.specific_material %}({{epigraphy.specific_material}}){% endif %}</td>
        </tr>
        {% endif %}
        
        {% if epigraphy.administrative_district %}
        <tr>
          <td><strong>Administrative district:</strong></td>
          <td>{{ epigraphy.get_administrative_district_display }}</td>
        </tr>
        {% endif %}
        
        {% if epigraphy.heigth %}
        <tr>
          <td><strong>Height:</strong></td>
          <td>{{ epigraphy.height }} CM</td>
        </tr>
        {% endif %}
        
        {% if epigraphy.length %}
        <tr>
          <td><strong>Length:</strong></td>
          <td>{{ epigraphy.length }} CM</td>
        </tr>
        {% endif %}
        
        {% if epigraphy.width_diameter %}
        <tr>
          <td><strong>Width/diameter:</strong></td>
          <td>{{ epigraphy.width_diameter }} CM</td>
        </tr>
        {% endif %}
        
        {% if epigraphy.gender %}
        <tr>
          <td><strong>Gender:</strong></td>
          <td>{{ epigraphy.gender }}</td>
        </tr>
        {% endif %}
        
       
        
        {% if epigraphy.state_of_preservation %}
        <tr>
          <td><strong>State of preservation:</strong></td>
          <td>{{ epigraphy.get_state_of_preservation_display }}</td>
        </tr>
        {% endif %}
        
        {% if epigraphy.motivation %}
        <tr>
          <td><strong>Motivation:</strong></td>
          <td>{{ epigraphy.motivation }}</td>
        </tr>
        {% endif %}
        
       
        
        {% if epigraphy.past_location %}
        <tr>
          <td><strong>Past location:</strong></td>
          <td>{{ epigraphy.past_location }}</td>
        </tr>
        {% endif %}
        
        {% if epigraphy.current_location %}
        <tr>
          <td><strong>Current location:</strong></td>
          <td>{{ epigraphy.current_location }}</td>
        </tr>
        {% endif %}
       
        {% if epigraphy.iconographic_elements.all %}
        <tr>
          <td><strong>Iconographic Elements:</strong></td>
          <td>
            <ul>
              {% for x in epigraphy.iconographic_elements.all %}
                <li>{{ x.name }}</li>
              {% endfor %}
            </ul>
          </td>
        </tr>
        {% endif %}
      </tbody>
    </table>
  </div>
</div>






<br>

<div class="accordion" id="epigraphyAccordion">
  <div class="accordion-item">
    <h2 class="accordion-header" id="descriptionHeader">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#descriptionCollapse" aria-expanded="false" aria-controls="descriptionCollapse">
        Description
      </button>
    </h2>
    <div id="descriptionCollapse" class="accordion-collapse collapse" aria-labelledby="descriptionHeader" data-bs-parent="#epigraphyAccordion">
      <div class="accordion-body">
        {{ epigraphy.description|safe }}
      </div>
    </div>
  </div>
</div>

  <div class="accordion-item">
    <h2 class="accordion-header" id="bibliographyHeader">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#bibliographyCollapse" aria-expanded="false" aria-controls="bibliographyCollapse">
        Bibliography
      </button>
    </h2>
    <div id="bibliographyCollapse" class="accordion-collapse collapse" aria-labelledby="bibliographyHeader" data-bs-parent="#epigraphyAccordion">
      <div class="accordion-body">
        {{ epigraphy.bibliography|safe }}
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="transcriptionHeader">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#transcriptionCollapse" aria-expanded="false" aria-controls="transcriptionCollapse">
        Transcription - Interpreted
      </button>
    </h2>
    <div id="transcriptionCollapse" class="accordion-collapse collapse" aria-labelledby="transcriptionHeader" data-bs-parent="#epigraphyAccordion">
      <div class="accordion-body">
        {{ epigraphy.transcription_interpreted|safe }}
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="transcriptionHeader">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#transcriptionCollapse" aria-expanded="false" aria-controls="transcriptionCollapse">
       Transcription - Diplomatic
      </button>
    </h2>
    <div id="transcriptionCollapse" class="accordion-collapse collapse" aria-labelledby="transcriptionHeader" data-bs-parent="#epigraphyAccordion">
      <div class="accordion-body">
        {{ epigraphy.transcription_diplomatic|safe }}
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="translationHeader">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#translationCollapse" aria-expanded="false" aria-controls="translationCollapse">
       Translation
      </button>
    </h2>
    <div id="translationCollapse" class="accordion-collapse collapse" aria-labelledby="translationHeader" data-bs-parent="#epigraphyAccordion">
      <div class="accordion-body">
        {{ epigraphy.translation|safe }}
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="apparatusHeader">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#apparatusCollapse" aria-expanded="false" aria-controls="apparatusCollapse">
        Apparatus
      </button>
    </h2>
    <div id="apparatusCollapse" class="accordion-collapse collapse" aria-labelledby="apparatusHeader" data-bs-parent="#epigraphyAccordion">
      <div class="accordion-body">
        {{ epigraphy.apparatus|safe }}
      </div>
    </div>
  </div>
</div>

<br>
<div>
  <div class="container">
    <p>
      {% if epigraphy.full_epidoc_xml %}
        <a href="{{ epigraphy.full_epidoc_xml.url }}" download>
            <button>Full Epidoc XML</button>
        </a>
    {% else %}
        <p>No file uploaded yet.</p>
    {% endif %}
      </p>
      

    

    

  </div>
</div>



















{% endblock %}
<script>
$(document).ready(function() {
    $("[data-fancybox]").fancybox();
});
</script>

 <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
 <script src="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-alpha.6.min.js"></script>